### ISSUE TITLE
Need Microsoft Integration

### ISSUE THREAD

**Issue by arnaudcharles1992** [hashicorp-forge/hermes#12]
Hi,

I'm kindly requesting to add Microsoft integration in addition to Google. 

Regards,

AC.

**Comment by anubhavmishra** [comment]
Thanks for the interest in Hermes! Unfortunately, we feel that the code base is currently too tied into Google Workspace where a PR enabling another "backend" would likely be too disruptive to accept. However, we are planning some refactors that would hopefully enable a PR like this. We are going to close this issue because we can't support this right now, but we're attaching the **integrations** label to this issue so we can revisit it when we could accept this sort of contribution. Thanks again!
