### ISSUE TITLE
Does Hermes support private documents?

### ISSUE THREAD

**Issue by deviancee** [hashicorp-forge/hermes#140]
Whenever I try to view a private google doc via hermes, I get two 302 redirects: first to `https://accounts.google.com/ServiceLogin` and then to `https://docs.google.com/accounts/SetOSID` which returns a 400

![image](https://user-images.githubusercontent.com/6137553/232001179-5f327846-b6d1-4fb0-8718-d993511debc0.png)

Is there any piece of setup that I am missing? Everything else works - including creating the docs

https://github.com/hashicorp-forge/hermes/blob/e60b43e20cc8cd1a72a91a6caa273da65774b35d/web/app/components/document/index.hbs#L21

**Comment by apparentlymart** [comment]
I see this behavior too and I suspect that it's related to how a browser has been configured to treat third-party cookies. 

Since Google Docs is being loaded into an iframe inside the Hermes UI, it's "third party" by the definitions in many browsers, and so Google's attempts to do cookie transfer by redirects through `accounts.google.com` fail.

I temporarily turned on third-party cookies in my browser and confirmed that the document loads in the iframe in that case, so that's a possible workaround if you really need the docs to load inside the iframe.

However, I typically just immediately use the "Open in Google" icon at the top of the left navbar to open the doc directly in its own browser tab, which I tend to prefer anyway since the Hermes toolbar is not needed unless you are actively requesting or giving approval.

**Comment by jfreda** [comment]
Hi @deviancee! Can you explain what you mean by a private Google Doc? Was this document created through Hermes? Also we recently released a new [version](https://github.com/hashicorp-forge/hermes/releases/tag/v0.1.0) of the app so it may be worth checking if this is still an issue for you.

**Comment by jeffdaley** [comment]
Hey @deviancee, I'm closing this since it's been inactive for more than a month. Feel free to reply and reopen it at any time. Thanks for your interest in the project!
