### ISSUE TITLE
How to use a service account

### ISSUE THREAD

**Issue by marccampbell** [hashicorp-forge/hermes#19]
The README.md and the config.hcl have references to creating a domain-wide delegated service account, and using it for production access. The instructions aren't clear though. Once the key is downloaded, how do I reference it in the config.hcl?

**Comment by anubhavmishra** [comment]
Hey @[marccampbell](https://github.com/marccampbell), good question. The documentation for the production deployment for Hermes is still a work in progress. In general, the domain-wide delegation service account can be used as a service user for Hermes to perform most Google API interactions. In order to use it, please follow the instructions in the README.md [here](https://github.com/hashicorp-forge/hermes#running-hermes-in-production) to create the service account and a new key (JSON type) for the service account and download it. Then populate the `config.hcl` with an `auth` block using the values from the downloaded JSON key. Here is an example what that might look like:

```hcl
google_workspace {
…..


 // auth is the configuration for interacting with Google Workspace using a
 // service account.
 auth {
   client_email = "{client-name}@{project-name}.iam.gserviceaccount.com"
   private_key  = "-----BEGIN PRIVATE KEY-----\....."
   subject      = "{hermes-service-user-name}@yourdomain.com"
   token_url    = "https://oauth2.googleapis.com/token"
 }
```
Here the `subject` is the Google Workspace user you want to use to perform Hermes operations like sending emails to users or updating document headers, etc.

**Comment by ad201125** [comment]
Hi @anubhavmishra, I am implementing hermes in production with a domain-wide delegated service account but when I am enabling the auth block I am getting the following error: 
I am getting this error when I am using the service account(hermes-demo@project-id.iam.gserviceaccount.com) as subject:
2024-07-23T13:06:06.273+0530 [INFO]  hermes: listening on 127.0.0.1:8000...
2024-07-23T13:06:48.092+0530 [WARN]  backoff error (retrying): error="error searching people directory: googleapi: Error 400: Must be a G Suite domain user., failedPrecondition" delay=309.662426ms
2024-07-23T13:06:48.670+0530 [WARN]  backoff error (retrying): error="error searching people directory: googleapi: Error 400: Must be a G Suite domain user., failedPrecondition" delay=690.576682ms
