### ISSUE TITLE
Non-Google usage

### ISSUE THREAD

**Issue by notpushkin** [hashicorp-forge/hermes#2]
Congrats on the launch! 🎉 

What would it take for Hermes to support “backends” other than Google Workspace? Say, something open source like ONLYOFFICE. From the looks of it, Google-related code is decoupled from the rest of the system, but I can't say on the first glance how tightly it's integrated.

Would you be interested in a PR implementing something like ONLYOFFICE support?

**Comment by kristiandrucker** [comment]
perhaps nextcloud integration to replace google workspace?

**Comment by j0sh3rs** [comment]
From a business usecase, integrating with Atlassian stacks would be HUGE (specifically confluence). Many orgs have docs spread between confluence/google/O365/GitHub/Gitlab, and supporting those backend types would be amazing for end users. Solves the "where's the best place to put this" and avoid's Atlassian's garbage search features

**Comment by michaelbogdan** [comment]
Another backend that would be nice is generic S3-style object storage for all those that do not use or do not want to use GSuite, M365 or such.

**Comment by jfreda** [comment]
Thanks for the interest in Hermes! Unfortunately, we feel that the code base is currently too tied into Google Workspace where a PR enabling another "backend" would likely be too disruptive to accept. However, we are planning some refactors that would hopefully enable a PR like this. We are going to close this issue because we can't support this right now, but we're attaching the **integrations** label to this issue so we can revisit it when we can accept this sort of contribution!
