### ISSUE TITLE
Make Algolia optional

### ISSUE THREAD

**Issue by jtolio** [hashicorp-forge/hermes#62]
For use cases where Hermes will be used for sensitive documents, it may not be preferred to send the full text of the documents off of the box to an indexing service (even if Algolia promises SOC2 compliance and so on). In these cases, it might be acceptable to give up document search. 

Is Algolia already optional if you don't want search? If not, that would be a useful option.

**Comment by the-maldridge** [comment]
Similarly, since Hermes is mostly just a go backend its easier to start with that for an experiment and then later onboard an additional vendor for search if people at an organization like it.  I know this is the way my organization prefers to do things, and I suspect it would be a lower bar for proofs of concept at other organizations as well.

**Comment by jfreda** [comment]
Hi @jtolio, thanks for the question! Algolia is currently not optional; basic Hermes functionality will likely not work without it. This may change in the somewhat near future where non-search Hermes functionality may work, however we do not have any plans to modify the frontend application to remove the search bar, etc.

So in a nutshell, Algolia is still very tied into the application, but in the future, the code may be at the point where you could fork the project if you'd like and remove search functionality with some effort.

**Comment by fishpen0** [comment]
Is this actually not scheduled to be worked on given the wider effort to move parts of algolia to postgres?
